coverage:
  status:
    project:
      default:
        threshold: 5
        target: auto
      plugin:
        target: 70%
        paths:
          - "!cli/"
        flags:
          - plugin
    patch: off
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null
flags:
  plugin:
    carryforward: true